"""Initial migration.

Revision ID: 72378859f9c2
Revises: 
Create Date: 2023-10-18 16:29:56.353088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72378859f9c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint('task_description_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.create_unique_constraint('task_description_key', ['description'])

    # ### end Alembic commands ###
