"""Create new four rows type of datetime.

Revision ID: a1f184022990
Revises: 72378859f9c2
Create Date: 2023-10-18 17:06:07.219448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1f184022990'
down_revision = '72378859f9c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
        batch_op.add_column(sa.Column('update_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('change_done_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('delete_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('delete_at')
        batch_op.drop_column('change_done_at')
        batch_op.drop_column('update_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
